server:
  port: 8001

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    sentinel:
      eager: true
      transport:
        port: 9001
        dashboard: localhost:8080

dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.easy.andProvider.service

  #Dubbo 服务暴露的协议配置，其中子属性 name 为协议名称，port 为协议端口（ -1 表示自增端口，从 20880 开始）
  protocol:
    name: dubbo
    port: -1

  #Dubbo 服务注册中心配置，其中子属性 address 的值 “spring-cloud://localhost”，说明挂载到 Spring Cloud 注册中心
  registry:
    address: nacos://127.0.0.1:8848?namespace=${nacos.namespace}

management:
  endpoints:
    web:
      exposure:
        include: "*"
