server:
  port: 8002

dubbo:
  registry:
    address: nacos://127.0.0.1:8848?namespace=${nacos.namespace}
  cloud:
    subscribed-services: xiezhu-provider

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    sentinel:
      eager: true
      transport:
        port: 9002
        dashboard: localhost:8080